# name: Environments
# run-name: Environments | Env - ${{ inputs.target-env}}
# on:
#   # push:
#   workflow_dispatch:
#     inputs:
#       target-env:
#         type: environment
#         default: staging
# jobs:
#   echo:
#     runs-on: ubuntu-latest
#     environment: ${{ inputs.target-env }}
#     env:
#       my-env-value: ${{ vars.MY_ENV_VALUE || 'default value'}}
#     steps:
#       - name: Echo Vars
#         run: |
#           echo "Env Variables: ${{ env.my-env-value}}"

name: Environments
on:
  # push:
  workflow_dispatch:
jobs:
  deploy-staging:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
      - name: Deploy to Staging
        run: echo "Deploying to Staging"
  e2e-tests:
    needs: [deploy-staging]
    runs-on: ubuntu-latest
    steps:
      - name: End to End testing
        run: echo "End to End testing completed."
  deploy-prod:
    needs: [e2e-tests]
    environment: Production
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Production
        run: echo "Deploying to Production"