name: Second Workflow
on:
  # push
  # pull_request:
  #   types:
  #     - opened
  #     - closed
  # workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"
jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: |
          echo "Event Type: ${{ github.event_name}}"