name: Matrices
on: 
  workflow_dispatch:
jobs:
  backword_compatibility:
    name: ${{ matrix.os}}-${{matrix.node-version}}
    runs-on: ${{ matrix.os}}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
        node-version:
          - 18.x
          - 20.x
          - 21.x
    steps:
      - name: Setup Node - ${{ matrix.node-version}}
        run: echo "Running tests on ${{ matrix.os}} and NodeJs ${{ matrix.node-version}}"