name: Context
on:
  push:
  workflow_dispatch:
jobs:
  echo-data:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        run: |
          echo "Event Name: ${{ github.Event}}"
          echo "Ref: ${{ github.ref_name}}"
          echo "SHA: ${{ github.sha}}"
          echo "Actor: ${{ github.actor}}"
          echo "Workflow: ${{ github.workflow}}"
          echo "Run ID: ${{ github.run_id}}"
          echo "Run Number: ${{ github.run_number}}"
      - name: Retrieve Variable
        run: echo ${{ vars.MY_VAR}}
