name: First Workflow
on:
  - push
  - workflow_dispatch
jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Say Helllo
        run: echo -e "Hello, World!\nWelcome to the world of DevOps"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      # - name: Failed step
      #   run: |
      #     echo "I will fail" 
      #     exit 1
      - name: Success Step
        run: |
          echo "I will succeed"
          exit 0
      - name: Say goodbye
        run: echo "Goodbye!"